### ISSUE TITLE
VNAV chooses to die

### ISSUE THREAD

**Issue by Mukund-2020** [Featherway/GeoFS-Autoland#1]
hello,
I tried out the routes you had posted in the server, most of the time, VNAV chooses to screw up, and puts me too high. Please fix this.

**Comment by nicolas377** [comment]
Thank you for your bug report. Can you elaborate further on how VNAV screwed up? Further information is necessary to determine the issue.

**Comment by Mukund-2020** [comment]
> Thank you for your bug report. Can you elaborate further on how VNAV screwed up? Further information is necessary to determine the issue.

it would take off normally, and while I am on approach, it would stop descending to the pre-set values, and continue cruising at whatever altitude I had set in the VNAV tab.

**Comment by nicolas377** [comment]
Could you try setting the VNAV cruising altitude to zero on final descent?

**Comment by Mukund-2020** [comment]
yah I can try

**Comment by nicolas377** [comment]
Let us know how it goes!

**Comment by nicolas377** [comment]
I just did a flight and found the problem. It's being worked on right now and should be out by the next patch!

**Comment by nicolas377** [comment]
We have solved the issue.
