### ISSUE TITLE
Add these three approach routes for TPA Airport in the upcoming update

### ISSUE THREAD

**Issue by ArinB007** [Featherway/GeoFS-Autoland#10]
RW 1L: ["","KTPA","",[["BAYZZ",27.862211111,-82.621369444,"3500",true,null],["WHITD",27.680088889,-82.624288889,"3000",true,null],["FITPA",27.731433333,-82.550225,"2600",true,null],["SNORK",27.830597222,-82.546863889,"2600",true,null],["WELIT",27.898147222,-82.544569444,"1300",true,null],["RW01L",27.971598,-82.54208,"-130",false,null],["BUTTER",null,null,"-130",false,null]]]

RW 19R: ["","KTPA","",[["FINKI",28.198169444,-82.575941667,"4000",true,null],["MUCRO",28.292675,-82.547602778,"3500",true,null],["MERRA",28.221216667,-82.533563889,"3000",true,null],["FADDI",28.156972222,-82.535758333,"3000",true,null],["JMBOB",28.094497222,-82.537888889,"2000",true,null],["RW19R",27.980399,-82.541786,"-120",false,null],["BUTTER",null,null,"-120",false,null]]]

RW 19L: ["","KTPA","",[["UFLIX",28.060222222,-82.262675,"3000",true,null],["ZPLIN",28.217344444,-82.326891667,"3000",true,null],["COBOX",28.222652778,-82.520183333,"3000",true,null],["POMSE",28.088002778,-82.524777778,"2000",true,null],["RW19L",27.977471,-82.528551,"-120",false,null],["BUTTER",null,null,"-120",false,null]]]

**Comment by nicolas377** [comment]
We will test the routes and hopefully add them in 0.2-0.

**Comment by nicolas377** [comment]
This is already in 0.2-0. Thanks for the routes!
