### ISSUE TITLE
FMC Problem

### ISSUE THREAD

**Issue by TheRealAceCoder** [Featherway/GeoFS-Autoland#11]
FMC Calculates distance to destination without waypoints when they are selected

**Comment by nicolas377** [comment]
This issue had been solved and will be implemented in the next update.

**Comment by TheRealAceCoder** [comment]
Whats going 0on lOL

**Comment by nicolas377** [comment]
It got fixed, then there was another bug that had to be fixed, which means now routes have to have coordinates in the BUTTER waypoint. Now its for real fixed.
