### ISSUE TITLE
One more autoland approach in request to be added for KTPA

### ISSUE THREAD

**Issue by ArinB007** [Featherway/GeoFS-Autoland#14]
["","KTPA","",[["HUMKI",27.736961111,-82.373891667,"3500",true,null],["JSTRM",27.691825,-82.422519444,"3000",true,null],["MUWTY",27.750325,-82.536255556,"2600",true,null],["ANAZE",27.850708333,-82.532852778,"2600",true,null],["ZELTO",27.909138889,-82.530866667,"1300",true,null],["RW01R",27.974082,-82.528668,"-120",false,null],["BUTTER",null,null,"-120",false,null]]]

**Comment by nicolas377** [comment]
We will test it and hopefully implement it in the next update.

**Comment by nicolas377** [comment]
This has been implemented in the next update.
