### ISSUE TITLE
Negative altitudes are marked as "Invalid" in the FMC

### ISSUE THREAD

**Issue by ArinB007** [Featherway/GeoFS-Autoland#2]
![Annotation 2020-07-18 103944](https://user-images.githubusercontent.com/68472257/87855160-61f89080-c8e4-11ea-91c9-fe70d9238240.png)

**Comment by nicolas377** [comment]
Thank you for your report. This issue will be worked on and should be fixed by the next update.

**Comment by nicolas377** [comment]
A fix has been found. Simply round the altitude to the nearest 10.

**Comment by nicolas377** [comment]
Negative altitudes are supported, but just like any other altitude, they must be rounded to a ten.
