### ISSUE TITLE
Aircraft floats too much and lands too close to the end of the runway

### ISSUE THREAD

**Issue by Jeronimo-GeoFS** [Featherway/GeoFS-Autoland#3]
When I try landing, the autoland maintains my altitude and doesn't touch down until I'm really close to the end of the runway and will most likely overrun. I'm not sure if it's just the route or the AP++, but it makes the aircraft touch down very late.

**Comment by nicolas377** [comment]
Thank you for your bug report. The optimal current fix to this issue in the current update is to set the final altitude in both the FMC and AP++ around 150 feet below the runway altitude. We will continue working on this and hopefully have a patch in the next update.

**Comment by nicolas377** [comment]
And remember to round the altitude, otherwise, the FMC rejects it.

**Comment by nicolas377** [comment]
It appears that the altitude just needed to be about 150 feet underground to keep it from hovering. We will keep researching the optimum altitude relative to the runway threshold and will include it in documentation in the next update.

**Comment by nicolas377** [comment]
This will be added to the documentation next update. Thank you very much for the report once more.
