### ISSUE TITLE
VNAV=0

### ISSUE THREAD

**Issue by BigBoiFlights-Ryan** [Featherway/GeoFS-Autoland#4]
i think you should make this as automated and hands free as possible, maybe have it change the VNAV cruise to 0 on the final waypoint or the semifinal one?

**Comment by nicolas377** [comment]
As in automatically?

**Comment by BigBoiFlights-Ryan** [comment]
yessir

**Comment by nicolas377** [comment]
Alright. Most automation will come in v 0.2-0

**Comment by BigBoiFlights-Ryan** [comment]
oh okay

**Comment by nicolas377** [comment]
This is no longer necessary as VNAV does no longer need manual input for descending.
