### ISSUE TITLE
premade route is kinda wonky

### ISSUE THREAD

**Issue by BigBoiFlights-Ryan** [Featherway/GeoFS-Autoland#6]
the route for KATL on RNWY 09R lines up on the runway at a slight angle and you have to turn it a little.

["","KATL","",[["ANDIY",33.63094,-84.86295,"7000",false,null],["DFINS",33.63118,-84.79389,"6000",false,null],["GGUYY",33.6314,-84.71884,"5000",false,null],["EEASY",33.63156,-84.64977,"4000",false,null],["BURNY",33.63173,-84.54941,"2700",false,null],["RW9R",33.631825,-84.437989,"870",false,null],["BUTTER",null,null,"870",false,null]]]

**Comment by nicolas377** [comment]
I will test this out myself and adjust the route accordingly. Do you have HD?

**Comment by BigBoiFlights-Ryan** [comment]
i do have HD

**Comment by nicolas377** [comment]
Alright

**Comment by nicolas377** [comment]
Found the problem. Working on it now.

**Comment by nicolas377** [comment]
It turns out that its just a part of the code of ap++. Its called exponentialSmoothing and generally should be on the centerline by the runway threshold. This is not a route issue and generally should be expected. Thanks for your report!
