### ISSUE TITLE
FMC included doesn't work

### ISSUE THREAD

**Issue by Airfrance14** [Featherway/GeoFS-Autoland#8]

**Comment by nicolas377** [comment]
Does it not load? Please send a screenshot of the console (F12)

**Comment by Airfrance14** [comment]
![Capturebtft](https://user-images.githubusercontent.com/51235286/88188376-0e65aa00-cc38-11ea-9526-a7a1ddcc2cf0.JPG)
![Capturecftdfffhgdftu](https://user-images.githubusercontent.com/51235286/88188397-158cb800-cc38-11ea-877c-97d4a47dd1bf.JPG)

**Comment by nicolas377** [comment]
Could you please send us a screenshot of the console?

**Comment by Airfrance14** [comment]
Can you explain to me what you mean?

**Comment by nicolas377** [comment]
Press F12, and it will open up an inspect menu. Select Console and send us a screenshot of that.

**Comment by Airfrance14** [comment]
![Capturekfgiufdgu](https://user-images.githubusercontent.com/51235286/88189325-3b668c80-cc39-11ea-85dd-c31f616d0663.JPG)

**Comment by nicolas377** [comment]
Could you try scrolling down and screenshotting anything in red?

**Comment by nicolas377** [comment]
This is a local problem.
